#!/usr/bin/env Rscript

#build_bipartite_networks.R
#Build bipartite networks from Jaccard matrices generated by compare_networks_jaccard.R
#Each bipartite network represents AD and Control communities (modules) connected by their Jaccard similarity.

#Usage:
#Rscript build_bipartite_networks.R \
#  --input_dir results_jaccard \
#  --output_dir results_bipartite \
#  --threshold 0.2

if (!requireNamespace("pacman", quietly = TRUE))
  install.packages("pacman", repos = "https://cloud.r-project.org")

ok <- pacman::p_load(
  tidyverse, igraph, ggraph, data.table, optparse, vroom
)

if (all(ok)) {
  message("All packages loaded correctly.")
} else {
  stop("Some packages did not load correctly.")
}

#Parser

option_list <- list(
  make_option(c("-i", "--input_dir"), type = "character", default = getwd(),
              help = "Directory with Jaccard_*.csv matrices", metavar = "character"),
  make_option(c("-o", "--output_dir"), type = "character", default = "./results_bipartite",
              help = "Output directory for bipartite graphs", metavar = "character"),
  make_option(c("-t", "--threshold"), type = "double", default = 0.2,
              help = "Minimum Jaccard similarity to include an edge [default: %default]")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

input_dir <- opt$input_dir
#opt$input_dir <- "/datos/rosmap/multiregion_networks/networks_final/networks_filtered/results_jaccard_1/"
output_dir <- opt$output_dir
#opt$output_dir <- "/datos/rosmap/multiregion_networks/networks_final/networks_filtered/bipartite_nets"
threshold <- opt$threshold
#opt$threshold <-0.25

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

message("Input dir: ", input_dir)
message("Output dir: ", output_dir)
message("Threshold: ", threshold)

dir.create(output_dir, showWarnings = FALSE)

#List files
files <- list.files(input_dir, pattern = "Jaccard_.*\\.csv$", full.names = TRUE)

#Function to create network, set a threshold and set attributes
process_jaccard_file <- function(file_path) {
  #Get regions by file name
  file_name <- basename(file_path)
  region <- str_extract(file_name, "(?<=Jaccard_).+?(?=_counts_)")
  #Read jaccard matrix Leer matriz Jaccard
  jaccard_mat <- vroom(file_path)
  #Get names
  ad_nodes <- jaccard_mat[[1]]
  ctrl_nodes <- colnames(jaccard_mat)[-1]
  #threshold
  threshold <- opt$threshold
  #Long format to set threshold
  edges_df <- jaccard_mat %>%
    pivot_longer(-1, names_to = "ctrl", values_to = "weight") %>%
    rename(ad = 1) %>%
    filter(weight >= threshold)
  #build graph from data frame
  g <- graph_from_data_frame(edges_df, directed = FALSE)
  #Set attribute (bipartite)
  V(g)$type <- str_detect(V(g)$name, "^ctrl")
  #Phenotype attribute
  V(g)$phenotype <- ifelse(str_detect(V(g)$name, "^ctrl"), "control", "AD")
  #Export as graphml
  output_file <- file.path(output_dir, paste0(region, "_bipartite.graphml"))
  write_graph(g, output_file, format = "graphml")
  
  cat("Network", output_file, "\n")
}

#Process all files
walk(files, process_jaccard_file)

#END