---
 title: "Network Analysis Report"
 output: html_document
 ---

```{r, echo=FALSE}
 if (!requireNamespace('pacman', quietly = TRUE)) install.packages('pacman')
 pacman::p_load(data.table, ggplot2, ggpubr, purrr)
 summary <- fread(' results/networks_summary.csv ')
 print(head(summary))
 ```

```{r, echo=FALSE}
 make_metric_plot <- function(df, metric, title, ylab, color) {
   ggplot(df, aes(x = as.factor(network), y = .data[[metric]], group = 1)) +
     geom_line() +
     geom_point(color = color, size = 2.5) +
     labs(title = title, x = 'Network', y = ylab) +
     scale_y_continuous(limits = c(max(df[[metric]])/4, max(df[[metric]]))) +
     theme_pubclean() +
     theme(legend.position = 'none', axis.text.x = element_text(angle=90, vjust=0.5, hjust=1))
 }
 ```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'n_nodes', 'Number of vertices (genes)', 'Number of vertices', 'cornflowerblue'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'n_edges', 'Number of edges', 'Number of edges', 'mediumpurple'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'n_components', 'Number of components', 'Number of components', 'slateblue'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'n_communities', 'Number of communities (INFOMAP)', 'Number of communities', 'navyblue'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'avg_path_len', 'Average path length', 'Average path length', 'olivedrab'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'clustering_global', 'Global clustering', 'Global clustering', 'red4'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'clustering_local_mean', 'Local clustering coefficient', 'Local clustering', 'lightpink4'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'diameter', 'Diameter', 'Diameter', 'red4'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'global_density', 'Global density', 'Density', 'lightsalmon'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'size_giant_component', 'Size of the giant component', 'Size', 'firebrick'))
```

```{r, echo=FALSE}
print(make_metric_plot(summary, 'Q_modularity', 'Q modularity', 'Q', 'seagreen'))
```

